# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotificationSE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationSE
    pod 'JCore'
    pod 'JPush'

end

target 'ZFBShouQian' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZFBShouQian

  target 'ZFBShouQianTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZFBShouQianUITests' do
    # Pods for testing
  end

end
